MVC_Uvod/Models/ErrorViewModel.cs
namespace MVC_Uvod.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Uvod/Models/Osoba.cs
namespace MVC_Uvod.Models
{
    public class Osoba
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public DateTime DatumRodjenja { get; set; }
    }
}

MVC_Uvod/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Uvod.Models;
using System.Diagnostics;

namespace MVC_Uvod.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_Uvod/Controllers/OsobaController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Uvod.Models;

namespace MVC_Uvod.Controllers
{
    public class OsobaController : Controller
    {
        [HttpGet]
        public IActionResult Index(Osoba o)
        {
            return View(o);
        }

        public string GetPodatak()
        {
            string pod = "";
            var query = Request.QueryString;
            if (query.HasValue)
            {
                pod = Request.Query["Dob"].ToString();
                pod += Request.Query["Pocetak"].ToString() + " do " + Request.Query["Kraj"].ToString();
            }
            return pod;
        }
        
        public string CookiePrijenos()
        {
            Response.Cookies.Append("Ime", "Ivan", new CookieOptions() { Expires = DateTime.Now.AddYears(1) });
            return "Cookie definiran";
        }

        public string ProcitajIme()
        {
            string cookie = "";
            if (Request.Cookies["Ime"] != null)
            {
                cookie = Request.Cookies["Ime"].ToString();
            }
            Response.Cookies.Delete("Ime");
            return cookie;
            
        }

        [HttpPost]
        public IActionResult OsobaPost()
        {
            var formstring = Request.Form;

            Osoba o = new Osoba();
            o.Ime = formstring["Ime"];
            o.Prezime = formstring["Prezime"];
            o.DatumRodjenja = DateTime.Parse(formstring["DatumRodjenja"]);

            return View("Index",o);
        }
    }
}

MVC_Uvod/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_Uvod/Views/Osoba/Index.cshtml
@model MVC_Uvod.Models.Osoba
@{
    ViewData["Title"] = "Index";
    ViewBag.Title = "Index";
}

<h1>Pozdrav, ja sam pogled @ViewBag.Title</h1>
<hr />

@if(Model.Ime != null)
{
    <p>Ime = @Model.Ime</p>
    <p>Prezime = @Model.Prezime</p>
    <p>Datum rodjenja = @Model.DatumRodjenja.ToString("dd.MM.yyyy")</p>
}
else
{
    <p>Hmm, nemam nikakve podatke, ajd ih unesi.</p>

    <table>
        <thead>
            <tr>
                <th scope="col"> <h4>Ovo je HTML forma s POST metodom</h4> </th>
                
                <th scope="col"> <h4>Ovo je HTML forma s GET metodom</h4> </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <form method="post" action="@Url.Action("OsobaPost","Osoba")">
                        <div class="form-group row">
                            <label for="Ime" class="col-sm-4 col-form-label">Ime:</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="Ime" name="Ime" placeholder="Unesi ime">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="Prezime" class="col-sm-4 col-form-label">Prezime:</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="Prezime" name="Prezime" placeholder="Unesi prezime">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="DatumRodjenja" class="col-sm-4 col-form-label">Datum rodjenja:</label>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" id="DatumRodjenja" name="DatumRodjenja">
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <button type="submit" class="btn btn-primary mb-2">Posalji podatke</button>
                        </div>
                    </form>
                </td>
                    
                <td>
                    <form method="get" action="@Url.Action("Index","Osoba")">
                        <div class="form-group row">
                            <label for="Ime" class="col-sm-4 col-form-label">Ime:</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="Ime" name="Ime" placeholder="Unesi ime">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="Prezime" class="col-sm-4 col-form-label">Prezime:</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="Prezime" name="Prezime" placeholder="Unesi prezime">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="DatumRodjenja" class="col-sm-4 col-form-label">Datum rodjenja:</label>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" id="DatumRodjenja" name="DatumRodjenja">
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <button type="submit" class="btn btn-primary mb-2">Posalji podatke</button>
                        </div>
                    </form>
                </td>
                
            </tr>
        </tbody>
    </table>
}

MVC_Uvod/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Uvod</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Uvod.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Uvod</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC_Uvod - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>